export const MESSAGE_LOADING = 'MESSAGE_LOADING';
export const MESSAGE_SUCCESS = 'MESSAGE_SUCCESS';
export const MESSAGE_ERROR = 'MESSAGE_ERROR';
export const MESSAGE_UPDATE = 'MESSAGE_UPDATE';
export const LOAD_MESSAGE_SUCCESS = 'LOAD_MESSAGE_SUCCES'
